"""'add_uninstall_feedback_table'

Revision ID: 21fe8cc61865
Revises: 85bfc532a74c
Create Date: 2026-06-19 15:46:17.927823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21fe8cc61865'
down_revision: Union[str, None] = '85bfc532a74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uninstall_feedbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('reasons', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=True)
    op.drop_table('uninstall_feedbacks')
    # ### end Alembic commands ###
