"""
CLI configuration loader.

Priority order (highest to lowest):
1. CLI flags (handled in cli.py)
2. Environment variables (ENVFORAGE_API_URL, etc.)
3. ~/.envforage/config.toml  (persistent user config)
4. .env file in current directory
5. Built-in defaults
"""
import sys
from pathlib import Path

from pydantic import Field, ValidationError
from pydantic_settings import BaseSettings, PydanticBaseSettingsSource, SettingsConfigDict, TomlConfigSettingsSource
from rich.console import Console

console = Console()

CONFIG_DIR = Path.home() / ".envforage"
CONFIG_FILE = CONFIG_DIR / "config.toml"

_DEFAULT_CONFIG_CONTENT = """\
# EnvForage CLI configuration file
# Generated by: envforge config init
#
# All values are optional — defaults are shown below.

[envforage]
# Base URL of the EnvForage backend API
# api_url = "http://localhost:8000"

# HTTP request timeout in seconds
# timeout = 30

# Enable automatic update prompts
# auto_update = false
"""


class CliSettings(BaseSettings):
    """
    EnvForage CLI settings.

    Loaded from (in priority order):
    - Environment variables (ENVFORAGE_API_URL, etc.)
    - ~/.envforage/config.toml
    - .env file in current directory
    - Built-in defaults
    """

    api_url: str = Field(default="http://localhost:8000", description="EnvForage backend API URL")
    timeout: int = Field(default=30, description="HTTP request timeout in seconds")
    auto_update: bool = Field(default=False, description="Enable automatic prompts/checks for updates")

    model_config = SettingsConfigDict(
        env_prefix="ENVFORAGE_",
        env_file=".env",
        env_file_encoding="utf-8",
        toml_file=str(CONFIG_FILE),
        extra="ignore",
    )

    @classmethod
    def settings_customise_sources(
        cls,
        settings_cls: type[BaseSettings],
        init_settings: PydanticBaseSettingsSource,
        env_settings: PydanticBaseSettingsSource,
        dotenv_settings: PydanticBaseSettingsSource,
        file_secret_settings: PydanticBaseSettingsSource,
    ) -> tuple[PydanticBaseSettingsSource, ...]:
        return (
            init_settings,
            env_settings,
            TomlConfigSettingsSource(settings_cls),
            dotenv_settings,
        )


def load_config() -> CliSettings:
    """Load configuration, gracefully handling validation errors with a clean message."""
    try:
        return CliSettings()
    except ValidationError as e:
        console.print(
            "[bold red]Configuration Error:[/bold red] The configuration file contains invalid data."
        )
        for error in e.errors():
            loc = ".".join(map(str, error["loc"]))
            console.print(f"  - [cyan]{loc}[/cyan]: {error['msg']}")
        sys.exit(1)


def init_config(force: bool = False) -> None:
    """
    Create ~/.envforage/config.toml with commented-out defaults.

    Args:
        force: Overwrite the file if it already exists.
    """
    if CONFIG_FILE.exists() and not force:
        console.print(
            f"[yellow]Config file already exists:[/yellow] {CONFIG_FILE}\n"
            "Use [bold]--force[/bold] to overwrite it."
        )
        return

    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CONFIG_FILE.write_text(_DEFAULT_CONFIG_CONTENT, encoding="utf-8")
    console.print(f"[green][+][/green] Config file created at [bold]{CONFIG_FILE}[/bold]")
    console.print("\nEdit it to set your preferences, for example:")
    console.print('  [cyan]api_url = "http://my-server:8000"[/cyan]')